foundriesio/composeapp

- Makefile
- cmd/composectl/cmd/check.go
- cmd/composectl/cmd/config.go
- cmd/composectl/cmd/inspect.go
- cmd/composectl/cmd/pull.go
- cmd/composectl/cmd/root.go
- pkg/compose/resolver.go
Allow user to define a default and command specific timeout for connection to container registry.
> Make connection timeout configurable

- Makefile
- cmd/composectl/cmd/root.go
- Allow to define a system-wide base config during compile time.
- The user defined config extends and/or overriddes the system one.
> Add ability to define a system-wide base config

- cmd/composectl/cmd/check.go
If images are hosted in docker.io registry then they can be referenced by a short (aka "familiar") URI format.
For example, "docker.io/library/nginx:stable-alpine" or "docker.io/homeassistant/home-assistant:stable" can be referenced as "nginx:stable-alpine" and  "homeassistant/home-assistant:stable" respectively.
The dockerd removes the "docker.io" or "docker.io/library" prefix when stores images in its store and as result returns the image URIs in the shorten format in a response to "http://localhost/images/json?all=1" request. For example, "nginx@sha256:<hash>" or
"homeassistant/home-assistant:<hash>".
The given change checks if the "familiar"/shorten image URI is present in the image map returned by dockerd in addition to checking the regular image URI as it is specified in a compose …
> check: Check "familiar" ref in addition to cannonical

- pkg/compose/v1/app_store.go
There is no point to continue with blob reading if a failure to open blob file occurs.
This improves error logging in case if an app is missing, or its manifest is missing to be precise.
Instead of `ERROR: invalid argument` the error log will look like:
`ERROR: failed to read app manifest: open <>/reset-apps/apps/http-server/7cc3a4c85b1d5ad40fe52c196b2a31388a010b720970480d11ee99dfa3dae113/manifest.json: no such file or directory`
> Improve err if app missing

- Makefile
- dev-shell.sh
- test/compose/Dockerfile
- test/compose/docker-compose.yml
- test/fixtures/composectl_cmds.go
- test/fixtures/layers_meta.go
- test/integration/edge_cases_test.go
- test/integration/smoke_test.go
Extend the test environment with functionality to generate metadata about image layers (size of extracted layers/blobs) and use the generated layer metadata in the `compose publish` testing. It helps us to cover the real-life use-case that occurs in the factory CI.
> Test publish with layers meta

- internal/app_manifest_builder.go
- internal/publish.go
- Move functionality related to compose app manifest creation into a
separate file and encapsulate it within a single object.
- Use the empty descriptor as a value of the app manifest config field
as the OCI image specification instructs.
> Empty descriptor as app manifest config

- go.mod
- go.sum
- pkg/compose/layers.go
Adjust the publish implementation so there are no any errors if the newer version (2.8.1) of the distribution is used as dependency.
> Switch to distribution 2.8.1

- cmd/composectl/cmd/publish.go
It is expected that a user specifies comma-separated list of image URIs, hence `StringSliceVar` type should be used instead of `StringArrayVar`.
> publish: Fix type of pinned images parameter

- cmd/composectl/cmd/compose.go
- cmd/composectl/cmd/manifest.go
- cmd/composectl/cmd/show.go
- pkg/compose/app.go
- pkg/compose/v1/app.go
Add a new command `show` with two sub-commands to print App manifest and compose file/project.
> show: Commands to output app manifest and compose

- cmd/composectl/cmd/check.go
- cmd/composectl/cmd/ps.go
- pkg/compose/app.go
- pkg/compose/v1/app.go
- Unify and simplify implementation of the app installation verification.
- Optionally, check whether an app is installed as part of the command verifying if an app is running.
> Improve app bundle integrity check

- cmd/composectl/cmd/check.go
- cmd/composectl/cmd/ps.go
- cmd/composectl/cmd/pull.go
- pkg/compose/app.go
- pkg/compose/v1/app.go
- pkg/compose/v1/app_store.go
- pkg/compose/v1/install.go
- test/compose/Dockerfile
- test/fixtures/composectl_cmds.go
- test/fixtures/preload-images.sh
- test/integration/edge_cases_test.go
Make `composectl` work if app is pulled by "aklite+skopeo".
1. Don't require all app blobs to install and start app if app is pulled by "aklite+skopeo". Require only those blobs that are mandatory to install and start app.
2. Don't require all app blobs during checking app "locally" in fully offline mode.
3. Skip app integrity check if app blobs are pulled by "aklite+skopeo".
3. Added a test to verify the aforementioned use-case.
> app: Skip app integrity check if pulled by skopeo

- pkg/compose/v1/app_store.go
Use hard links instead of symlinks for an app bundle archive and app manifest in the app directory of an overall app store.
Using symlinks leads to removal of these two artifacts if downgrade or rollback to LmP version <=93 occurs. The previous aklite versions do not expect these two blobs in the blob store, they expect them in the app directory of the store, so the prune operation removes them from the blob store, and, as the result, the symlinks defined in the app directory become invalid. It makes aklite thinks that app is not fully fetched and starts the "sync" update which never succeeds, so aklite ends up in doing eternal "sync" updates.
Replacing the symlinks with hard links fixes the issue since the blobs are not removed because they have two links/references, one in the blobs …
> app_store: Avoid app bundle removal if blob store is pruned

- pkg/compose/v1/app_store.go
The app store's blob provider should be used for the app pruning, otherwise app pulled by `skopeo` won't be loadable.
> prune: Use correct blob provider

- pkg/compose/v1/publish.go
It turned out that some of the 3rd party registries changes the media type of a blob/layer specified by a client. Therefore, we need explicitly set the media type to `application/octet-stream` after the app blob has been published before creating an app's manifest. Using media type other than `application/octet-stream` breaks the older versions of `aklite` and `composectl` that explicitly expects the given media type.
> publish: Enforce media type of app bundle layer

- cmd/composectl/cmd/publish.go
Set the `--layers-manifest` to `false` by default so the `manifests` field with references to app layers' meta is not added to an app manifest. Adding this field to an app manifest makes it OCI incompatible.
> publish: Publish OCI compliant manifest by default

- cmd/composectl/cmd/ps.go
- cmd/composectl/cmd/uninstall.go
Don't print log message about found external image or app if a `json` output format is specified.
> ps: Don't print info about ext images if json output

- cmd/composectl/cmd/check.go
- cmd/composectl/cmd/compose.go
- cmd/composectl/cmd/config.go
- cmd/composectl/cmd/inspect.go
- cmd/composectl/cmd/manifest.go
- cmd/composectl/cmd/pull.go
- cmd/composectl/cmd/root.go
- pkg/compose/auth.go
- pkg/compose/resolver.go
Add a timeout for setting TLS/TCP connection to an auth server that occurs at an initial phase of transferring data from a container registry.
> auth: Add connection timeout for auth requests

- pkg/compose/v1/app.go
- pkg/compose/v1/publish.go
- test/fixtures/composectl_cmds.go
- test/integration/edge_cases_test.go
- When the published app lacks bundle indexes, fall back to indexing
the bundle on the fly. This enables checking whether the app's
compose project is installed and whether it is valid.
- This is also necessary to determine which version of the app is
actually installed when multiple versions are fetched, since all
versions share the same compose directory.
- Add an integration test to verify this behavior: when two versions
of the same app are published without bundle indexes, ensure we
correctly detect which version is installed and running.
> Check compose if no indexes

- .github/workflows/ci.yml
- .golangci.yml
- cmd/composectl/cmd/check.go
- cmd/composectl/cmd/update/fetch.go
- cmd/composectl/cmd/update/status.go
- go.mod
- internal/progress/reporter_test.go
- pkg/compose/app.go
- pkg/compose/blob.go
- pkg/compose/image_loader.go
- pkg/compose/status.go
- pkg/compose/tree.go
- pkg/update/fetch.go
- pkg/update/init.go
- pkg/update/update.go
- test/compose/Dockerfile
- test/integration/edge_cases_test.go
- test/integration/image_loading_test.go
- test/integration/update_test.go
Set of changes aimed to cleanup and improve the code related to tracking blob download progress.
- Remove obsolete type representing blobs status.
- Use the same structure to represent a blob fetch status for both `composectl pull/check` and `composectl update` commands.
- Switch to golang v1.24 and golangci-lint v2.1.6.
- Improve output of update fetching progress.
> Cleanups and improvements

- go.mod
- pkg/compose/fetch.go
- Set the minimum required golang version to 1.22.12 to avoid build failure during LmP bitbaking since the current/main version of LmP/FF uses this version of golang.
- Fix an issue with returning error if context is cancelled.
> Require lower golang ver

- pkg/compose/fetch.go
Make sure the app pull does not hang in case very fast copying when the read monitor starts listening for events after the pull completes.
> Fix concurrency issue

- cmd/composectl/cmd/run.go
- pkg/compose/start.go
- pkg/compose/stop.go
- pkg/update/start.go
- pkg/update/update.go
- test/fixtures/composectl_cmds.go
Enhance the API function to start apps and use it in both `composectl run` and `composectl update start` commands (avoid code duplication and encapsulate apps start functionality).
It allows to improve `fioup update|start` command output by making it less verbose and more concise.
Some minor fixes.
Allow stopping apps even if some of them are not installed.
> Unify and improve app start

- pkg/update/status_printer.go
The rounded `elapsed` time can be zero, so we need to make sure it is not before dividing by it.
> status_printer: Fix average speed calculation
